### ISSUE TITLE
Sample to create tables / dynamics tables

### ISSUE THREAD

**Issue by papyr** [tallesl/QuickQuery#1]
Hello, very nice wrapper :+1:  can you tell me how to implement a create tables, I am importing a list of tables and columns from excel, and want to use the wrapper to create the tables in sql server.

thanks

**Comment by tallesl** [comment]
You can create tables by giving the SQL statement to the `Change` method, such as:

``` cs
new Query("MyConnectionStringName").Change(@"
    CREATE TABLE Foo (
        Bar INT,
        Qux BIT
    )
");
```

But you have to manually write the query, there's no _automagical_ construct that makes the SQL statement for you.
